OtelRez.MVC/Models/VMs/Hesap/GirisVM.cs
using System.ComponentModel.DataAnnotations;

namespace OtelRez.MVC.Models.VMs.Hesap
{
    public class GirisVM
    {
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Mail adresi girilmesi zorunludur")]
        public string Mail { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Şifre  girilmesi zorunludur")]
        public string Sifre { get; set; }
        public bool RememberMe { get; set; } = false;
    }
}

OtelRez.MVC/Models/VMs/Hesap/KayitVM.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using OtelRez.BL.Attributes;

namespace OtelRez.MVC.Models.VMs.Hesap
{
    public class KayitVM
    {
        //private string _tel;

        [Required(ErrorMessage = "Ad alanı zorunludur")]
        [MinLength(3, ErrorMessage = "En az 3 karakter olmalıdır")]
        [MaxLength(15, ErrorMessage = "En fazla 15 karakter olmalıdır")]
        public string Adi { get; set; }

        [Required(ErrorMessage = "Soyad alanı zorunludur")]
        [MinLength(2, ErrorMessage = "En az 2 karakter olmalıdır")]
        [MaxLength(15, ErrorMessage = "En fazla 15 karakter olmalıdır")]
        public string Soyadi { get; set; }

        [Required(ErrorMessage = "Email alanı zorunludur")]
        [DataType(DataType.EmailAddress)]
        public string Mail { get; set; }

        [Required(ErrorMessage = "Telefon alanı zorunludur")]
        [StringLength(11, ErrorMessage = "Telefon numarası 11 karakter olmalıdır")]
        [RegularExpression("^[0-9]{11}$", ErrorMessage = "Telefon numarası sadece 0-9 arasında rakamlardan oluşmalı ve 11 karakter olmalıdır")]
        [DataType(DataType.PhoneNumber)]
        public string Tel { get; set; }

        [Required(ErrorMessage = "Doğum tarihi alanı zorunludur")]
        [DataType(DataType.Date)]
        public DateOnly DogumTarihi { get; set; }

        [Required(ErrorMessage = "Şifre alanı zorunludur")]
        [MinLength(3, ErrorMessage = "En az 3 karakter olmalıdır")]
        [MaxLength(16, ErrorMessage = "En fazla 16 karakter olmalıdır")]
        [DisplayName("Şifre")]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }
    }
}

OtelRez.MVC/Models/VMs/Hesap/SifremiUnuttumVM.cs
using System.ComponentModel.DataAnnotations;

namespace OtelRez.MVC.Models.VMs.Hesap
{
    public class SifremiUnuttumVM
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

OtelRez.MVC/Controllers/HesapController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.Routing;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using OtelRez.BL.Managers.Abstract;
using OtelRez.BL.Managers.Concrete;
using OtelRez.DAL.DbContexts;
using OtelRez.Entity.Entities.Concrete;
using OtelRez.MVC.Models.VMs.Hesap;
using System.Security.Claims;

namespace OtelRez.MVC.Controllers
{
    [Authorize]
    public class HesapController(IManager<Kullanici> kullaniciManager, IManager<PersonelGiris> personelGirisManager, IManager<Personel> personelManager, INotyfService notyfService) : Controller
    {
        private readonly AppDbContext _db = new AppDbContext();
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Giris()
        {
            GirisVM girisVM = new GirisVM();
            return View(girisVM);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Giris(GirisVM girisVM)
        {
            var user = kullaniciManager.GetAllInclude(p => p.Mail == girisVM.Mail && p.Sifre == girisVM.Sifre, p => p.Role).FirstOrDefault();
            var personel = personelGirisManager.GetAllInclude(p => p.Mail == girisVM.Mail && p.Sifre == girisVM.Sifre).FirstOrDefault();

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier,girisVM.Mail)
            };

            if (user != null)
            {
                claims.Add(new Claim("userId", user.Id.ToString()));  // userId'yi claim olarak ekliyoruz
            }

            if (personel != null)
            {
                claims.Add(new Claim("personelId", personel.Id.ToString()));  // personelId'yi claim olarak ekliyoruz
            }

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var authenticationProperty = new AuthenticationProperties()
            {
                IsPersistent = girisVM.RememberMe
            };

            var userPrincipal = new ClaimsPrincipal(claimsIdentity);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                userPrincipal, authenticationProperty);

            if (user == null)
            {
                if (personel == null)
                {
                    notyfService.Error("Mail ya da şifre hatalı.");
                    return View(girisVM);
                }

                else
                {
                    var personelRoleId = personelManager.GetById(personel.PersonelId);

                    if (personelRoleId.RoleId == 1)
                    {
                        return RedirectToAction("Index", "Admin", new { Area = "Admin" });
                    }

                    else if (personelRoleId.RoleId == 2)
                    {
                        return RedirectToAction("Iletisim", "Sayfa");
                    }

                    else
                    {
                        notyfService.Error("Geçersiz Giriş Bilgisi.");
                        return View(girisVM);
                    }
                }
            }

            return RedirectToAction("Index", "Home"); ;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Cikis()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Kayit()
        {
            KayitVM kayitVM = new KayitVM();
            return View(kayitVM);
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult Kayit(KayitVM kayitVM)
        {
            if (!ModelState.IsValid)
            {
                notyfService.Error("Düzeltilmesi gereken yerler var");
                return View(kayitVM);
            }

            var kayitli = kullaniciManager.GetAllInclude(p => p.Mail == kayitVM.Mail || p.Tel == kayitVM.Tel).FirstOrDefault();
            if (kayitli != null)
            {
                notyfService.Warning("Bu Email hesabı ya da telefon numarası daha önce kayıt olmuş.");
                return View(kayitVM);
            }

            Kullanici kullanici = new Kullanici();
            kullanici.Adi = kayitVM.Adi;
            kullanici.Soyadi = kayitVM.Soyadi;
            kullanici.Mail = kayitVM.Mail;
            kullanici.Tel = kayitVM.Tel;
            kullanici.DogumTarihi = kayitVM.DogumTarihi;
            kullanici.Sifre = kayitVM.Sifre;

            kullaniciManager.Create(kullanici);

            notyfService.Success("İşlem Başarılı");

            return RedirectToAction("Giris", "Hesap");
        }
    }
}

OtelRez.MVC/Controllers/SifreController.cs
using Microsoft.AspNetCore.Mvc;
using OtelRez.BL.Managers.Abstract;

namespace OtelRez.MVC.Controllers
{
    public class SifreController : Controller
    {
        private readonly IUserService _userService;

        public SifreController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SifremiUnuttum()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SifremiUnuttum(string email)
        {
            if (string.IsNullOrEmpty(email))
            {
                ViewBag.Message = "Email adresi boş olamaz.";
                return View();
            }

            bool isSuccess = _userService.SendForgotPasswordEmail(email);
            ViewBag.Message = isSuccess ? "Şifreniz mail adresinize gönderildi." : "Kullanıcı bulunamadı.";
            return View();
        }
    }
}

OtelRez.MVC/Views/Hesap/Giris.cshtml
@using OtelRez.MVC.Models.VMs.Hesap
@model GirisVM

<title>Giriş</title>

<div class="row">
    <div class="container">
        <div class="login-box">
            <div class="card">
                <div class="card-body login-card-body">
                    <p class="login-box-msg">Giriş için formu doldurun</p>

                    <form asp-action="Giris" method="post">
                        <div class="input-group mb-3">
                            <input asp-for="Mail" class="form-control" placeholder="Mail">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>

                        <div class="input-group mb-3">
                            <input asp-for=Sifre class="form-control" placeholder="Şifre">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-8">
                                <div class="">
                                    <input asp-for="RememberMe">
                                    <label for="remember">
                                        Beni Hatırla
                                    </label>
                                </div>
                            </div>

                            <div class="col-4">
                                <button type="submit" class="btn btn-primary btn-block">Giriş Yap</button>
                            </div>
                        </div>
                    </form>

                    <p class="mb-1">
                        <a  asp-controller="Sifre" asp-action="SifremiUnuttum">Şifremi Unuttum</a>
                    </p>
                    <p class="mb-0">
                        <a asp-controller="Hesap" asp-action="Kayit">Üye Ol</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

OtelRez.MVC/Views/Hesap/Kayit.cshtml
@using OtelRez.MVC.Models.VMs.Hesap
@model KayitVM

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kayıt</title>
    <link rel="stylesheet" href="~/RegisterTemp/style.css">
</head>
<body>
    <div class="register-body">
        <div class="container-register">
            <!-- Title section -->
            <div class="title">Registration</div>
            <div class="content">
                <!-- Registration form -->
                <form asp-action="Kayit" method="post">
                    <div class="user-details">
                        <!-- Input for Name -->
                        <div class="input-box">
                            <span asp-validation-for="Adi" class="details">Adınız</span>
                            <input asp-for="Adi" placeholder="Adınızı Giriniz" required>
                        </div>
                        <!-- Input for Surname -->
                        <div class="input-box">
                            <span asp-validation-for="Soyadi" class="details">Soyadınız</span>
                            <input asp-for="Soyadi" placeholder="Soyadınızı Giriniz" required>
                        </div>
                        <!-- Input for Email -->
                        <div class="input-box">
                            <span asp-validation-for="Mail" class="details">Mailiniz</span>
                            <input asp-for="Mail" type="email" placeholder="Mailinizi Giriniz" required>
                        </div>
                        <!-- Input for Phone Number -->
                        <div class="input-box">
                            <span asp-validation-for="Tel" class="details">Telefon Numaranız</span>
                            <input asp-for="Tel" placeholder="0(50*)*** ** **" required>
                        </div>
                        <!-- Input for Birth date -->
                        <div class="input-box">
                            <span asp-validation-for="DogumTarihi" class="details">Doğum Tarihiniz</span>
                            <input asp-for="DogumTarihi" type="date" value="2000-01-01" required>
                        </div>
                        <!-- Input for Password -->
                        <div class="input-box">
                            <span asp-validation-for="Sifre" class="details">Şifreniz</span>
                            <input asp-for="Sifre" type="password" placeholder="Şifrenizi Giriniz" required>
                        </div>
                    </div>
                    <!-- Submit button -->
                    <div class="button">
                        <input type="submit" value="Üye Ol">
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>